import = [
    "~/.config/alacritty/themes/themes/deep_space.toml"
]

[font]
# normal = { family = "RobotoMono Nerd Font", style = "Regular" }
# normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
normal = { family = "FiraCode Nerd Font", style = "Light" }
size = 19 
# offset = { y = 4 }
# glyph_offset = { y = 2 }

[cursor]
style = { shape = "Block" }

[env]
TERM = "xterm-256color"
